name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: pavi2410/Webview-to-APK@v1.2
        with:
          title: "Our SMM"
          url: "https://oursmm.top"
